### ISSUE TITLE
template copy questions

### ISSUE THREAD

**Issue by david-lippert** [gw-ospo/jupyter-book-template#14]
I'm working through the template to create a new tutorial and documenting questions I have along the way.

Is the first line in Setup pointing to the link  "[Make a copy](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) of this template repository", the same as clicking "use this template -> create a new repository"?

<img width="180" alt="Screenshot 2024-05-21 at 2 38 22 PM" src="https://github.com/gw-ospo/jupyter-book-template/assets/8987916/5093fc78-2e3f-4632-b89f-1cda3438cadd">

If yes, should I select "Include all branches" or not.
<img width="557" alt="Screenshot 2024-05-21 at 2 34 55 PM" src="https://github.com/gw-ospo/jupyter-book-template/assets/8987916/1a971462-28ca-4169-ae92-c25fe9585944">

more to come...

Not sure if this is my user error or something that needs to be added to the docs.
My github action failed because I had not enabled github pages in my settings.  Any instructions about best practices for setting this up would be appreciated.
<img width="791" alt="Screenshot 2024-05-21 at 6 00 37 PM" src="https://github.com/gw-ospo/jupyter-book-template/assets/8987916/de6e8f6e-6f58-4406-b1ac-2d5bfff8714f">

**Comment by s2t2** [comment]
Hi @david-lippert see answers below:

Yes, that is how to create a copy of the template.

Including all branches shouldn't matter that much either way. Probably no need to do so (can keep unchecked / no action required).

If you are using the most recent version of the repo, there is a note in the setup section about the GitHub pages setup step  as well as a "Deploying" section at the bottom of the page with more information 

> NOTE: the GitHub Actions build for your new repository may be failing initially, until you configure GitHub Actions (see "Deploying" section below)

> In your GitHub repository's settings, under the "pages" settings, configure GitHub Pages, specifically choosing to deploy from "GitHub Actions" source.

Let me know if you have ideas to make this information more clear or display more prominently to reduce confusion. Perhaps we can add some of the screenshots you took.
