### ISSUE TITLE
explain changes needed to `_config.yml`

### ISSUE THREAD

**Issue by labarba** [gw-ospo/jupyter-book-template#4]
Users need to know how to change the `_config.yml` file for their book. Note that file in template repo wasn't fully updated from generic example: url and folder need fixing.

**Comment by labarba** [comment]
see line where url is set, and path below: https://github.com/gw-ospo/jupyter-book-template/blob/977ae21ae78e5f85a45cf63a81156493ddf8fb08/example-book/_config.yml#L24

**Comment by s2t2** [comment]
Hosting the OSPO logo here. Maybe we can point to this url instead of including the logo in the repo (providing a more lightweight approach for non-OSPO users)

![gw_iddol_ospo_2c](https://github.com/gw-ospo/jupyter-book-template/assets/1328807/3a7c7320-422d-443a-bf05-20896fd5e2fd)
